#Understanding stages

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'


stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build FirstJob
    - bash: echo $(Build.BuildNumber)
    - bash: echo $(Build.BuildId)
    - bash: echo $(Build.SourceBranchName)
    - bash: echo $(Build.SourcesDirectory)
    - bash: echo $(System.DefaultWorkingDirectory)
    - bash: ls -R $(System.DefaultWorkingDirectory)
    - bash: echo $(Build.ArtifactStagingDirectory)
    - bash: echo $(Agent.JobStatus)
    - bash: echo $(Agent.Name)
    - bash: echo $(Agent.OS)
    - bash: java -version
    - bash: node --version
    - bash: python --version
    - bash: mvn -version
    - bash: ls -R $(Build.ArtifactStagingDirectory)
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          **/*.yaml
          **/*.tf
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - bash: ls -R $(Build.ArtifactStagingDirectory)

# - stage: DevDeploy
#   dependsOn: Build
#   variables:
#     environment: Dev
#   jobs:
#   - job: DevDeployJob
#     steps:
#     - bash: echo $(environment)DevDeployJob
# - stage: QADeploy
#   dependsOn: Build
#   jobs:
#   - job: QADeployJob
#     steps:
#     - bash: echo QADeployJob
# - stage: ProdDeploy
#   dependsOn:
#   - DevDeploy
#   - QADeploy
#   jobs:
#   - job: ProdDeployJob
#     steps:
#     - bash: echo ProdDeployJob



